# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Deterministic Python Scorer for Radiopharmaceutical Target Prioritisation.

Design Principle 1.3: Scores are computed in Python, never generated by a model.
Design Principle 1.4: Missing data is not zero.
Design Principle 1.5: Withheld scores when core evidence is absent.
"""

from pathlib import Path
from typing import Any
import yaml
from radiopharm_target_agent.schemas import (
    Claim,
    EvidenceBundle,
    ScoreAxisResult,
    Scorecard,
    SourceRef,
)

DEFAULT_WEIGHTS_FILE = Path(__file__).parent.parent / "weights.yaml"


def load_scoring_config(config_path: str | Path | None = None) -> dict[str, Any]:
    """Loads weights.yaml configuration."""
    path = Path(config_path) if config_path else DEFAULT_WEIGHTS_FILE
    if not path.exists():
        alt_path = Path("weights.yaml")
        if alt_path.exists():
            path = alt_path

    with open(path, "r") as f:
        return yaml.safe_load(f)


def _score_tumour_selectivity(
    evidence: EvidenceBundle, tier_caps: dict[str, float]
) -> ScoreAxisResult:
    """Computes tumour-to-normal selectivity score capped by evidence tier."""
    tn_claim = evidence.expression.get("tumour_vs_normal_ratio")
    if not tn_claim or tn_claim.status in ["unavailable", "not_measured"]:
        return ScoreAxisResult(
            axis_name="tumour_selectivity",
            score=None,
            weight=0.20,
            weighted_score=None,
            confidence="low",
            status="withheld",
            rationale="score withheld — expression evidence unavailable",
            caveats=["Expression data was unavailable or withheld."],
            sources=[],
        )

    tn_val = float(tn_claim.value) if tn_claim.value is not None else 1.0
    tier = tn_claim.evidence_tier
    cap = tier_caps.get(tier, 7.0)

    # Scale T/N ratio: T/N >= 30 is 10.0, T/N <= 1.0 is 0.0
    if tn_val >= 30.0:
        raw_score = 10.0
    elif tn_val >= 20.0:
        raw_score = 8.5 + (tn_val - 20.0) * 0.15
    elif tn_val >= 10.0:
        raw_score = 7.0 + (tn_val - 10.0) * 0.15
    elif tn_val >= 3.0:
        raw_score = 4.0 + (tn_val - 3.0) * 0.42
    elif tn_val >= 1.5:
        raw_score = 2.0 + (tn_val - 1.5) * 1.33
    else:
        raw_score = max(0.0, (tn_val - 1.0) * 2.0)

    final_score = min(raw_score, cap)
    final_score = round(final_score, 2)

    rationale = (
        f"Tumour-to-normal contrast ratio of {tn_val:.1f}x. "
        f"Raw selectivity score ({raw_score:.1f}) capped at {cap:.1f} by evidence tier '{tier}'."
    )

    return ScoreAxisResult(
        axis_name="tumour_selectivity",
        score=final_score,
        weight=0.20,
        weighted_score=round(final_score * 0.20, 3),
        confidence=tn_claim.confidence,
        status="scored",
        rationale=rationale,
        caveats=tn_claim.caveats,
        sources=tn_claim.sources,
    )


def _score_oar_safety_margin(
    evidence: EvidenceBundle,
    isotope: str,
    oar_weights: dict[str, float],
    mod_config: dict[str, Any],
) -> ScoreAxisResult:
    """
    Computes Organ-at-Risk (OAR) safety margin score weighted by organ radiosensitivity.
    Strictness is isotope-modulated (stricter for alpha emitters).
    """
    is_alpha = isotope in ["Ac-225", "Pb-212"]
    strictness = 1.30 if is_alpha else 1.00

    sources: list[SourceRef] = []
    caveats: list[str] = []
    total_penalty = 0.0

    for organ, claim in evidence.oar_panel.items():
        if claim.sources:
            sources.extend(claim.sources)
        if claim.caveats:
            caveats.extend(claim.caveats)

        if claim.status == "measured" and claim.value is not None:
            val = float(claim.value)
            weight = oar_weights.get(organ, 1.0)

            # Proportional penalty scaled against 50 TPM reference
            # Penalizes high normal expression without inappropriately collapsing moderate expression to 0
            penalty = min(6.0, (val / 50.0) * 1.5) * weight * strictness
            total_penalty += penalty
        elif claim.status == "not_measured":
            caveats.append(f"Organ '{organ}' is not_measured in reference atlas.")

    score = max(0.0, 10.0 - total_penalty)
    score = round(min(10.0, score), 2)

    rationale = (
        f"OAR safety margin evaluated across {len(evidence.oar_panel)} critical organs. "
        f"Calculated penalty of {total_penalty:.2f} (Strictness multiplier {strictness}x for {isotope})."
    )

    # Deduplicate sources by identifier
    unique_sources = {s.identifier: s for s in sources}.values()

    return ScoreAxisResult(
        axis_name="oar_safety_margin",
        score=score,
        weight=0.20,
        weighted_score=round(score * 0.20, 3),
        confidence="high",
        status="scored",
        rationale=rationale,
        caveats=list(set(caveats)),
        sources=list(unique_sources),
    )


def _score_malignant_cell_specificity(evidence: EvidenceBundle) -> ScoreAxisResult:
    """Scores single-cell compartment localization."""
    claim = evidence.single_cell.get("sc_dominant_compartment")
    if not claim:
        return ScoreAxisResult(
            axis_name="malignant_cell_specificity",
            score=5.0,
            weight=0.15,
            weighted_score=round(5.0 * 0.15, 3),
            confidence="low",
            status="scored",
            rationale="Single-cell compartment uncharacterized; assigned neutral baseline.",
            sources=[],
        )

    compartment = str(claim.value) if claim.value else ""
    if "malignant" in compartment or "luminal" in compartment or "ductal" in compartment:
        score = 9.5
        rationale = "High malignant-cell compartment specificity confirmed via single-cell transcriptomics."
    elif "fibroblast" in compartment or "caf" in compartment:
        score = 4.0
        rationale = "Target localized predominantly to cancer-associated fibroblasts (CAFs / stroma), not malignant epithelial cells."
    elif "immune" in compartment:
        score = 1.0
        rationale = "Target restricted to tumor-infiltrating immune cells."
    else:
        score = 3.0
        rationale = f"Dominant compartment '{compartment}' is non-malignant parenchyma."

    return ScoreAxisResult(
        axis_name="malignant_cell_specificity",
        score=score,
        weight=0.15,
        weighted_score=round(score * 0.15, 3),
        confidence=claim.confidence,
        status="scored",
        rationale=rationale,
        caveats=claim.caveats,
        sources=claim.sources,
    )


def _score_heterogeneity_penalty(
    evidence: EvidenceBundle, isotope: str
) -> ScoreAxisResult:
    """
    Computes heterogeneity score.
    Isotope modulated:
    - Beta (Lu-177): cross-fire range tolerates moderate heterogeneity (multiplier 0.80 penalty).
    - Alpha (Ac-225): short track length requires uniform cellular expression (multiplier 1.40 penalty).
    """
    is_alpha = isotope in ["Ac-225", "Pb-212"]
    pct_claim = evidence.single_cell.get("sc_percent_positive_malignant")
    bimodal_claim = evidence.single_cell.get("sc_bimodality")

    sources: list[SourceRef] = []
    if pct_claim:
        sources.extend(pct_claim.sources)

    pct_pos = float(pct_claim.value) if pct_claim and pct_claim.value is not None else 85.0
    is_bimodal = bool(bimodal_claim.value) if bimodal_claim and bimodal_claim.value is not None else False

    # Base homogeneity score
    if pct_pos >= 85.0 and not is_bimodal:
        base_score = 9.5
    elif pct_pos >= 70.0:
        base_score = 7.5 if not is_bimodal else 6.0
    elif pct_pos >= 50.0:
        base_score = 5.5 if not is_bimodal else 4.0
    else:
        base_score = 2.5

    # Modulate by isotope
    if is_alpha:
        # Alpha is severely penalized for subclonal cold spots
        penalty = (10.0 - base_score) * 1.40
        score = max(0.0, 10.0 - penalty)
        rationale = (
            f"Alpha emitter context ({isotope}): High LET tracks require uniform per-cell expression. "
            f"{pct_pos:.1f}% positive malignant cells results in heterogeneity score {score:.1f} (1.4x alpha penalty)."
        )
    else:
        # Beta cross-fire effect bridges cold spots
        penalty = (10.0 - base_score) * 0.80
        score = max(0.0, 10.0 - penalty)
        rationale = (
            f"Beta emitter context ({isotope}): 1-2mm cross-fire range partially compensates for intratumoural heterogeneity. "
            f"{pct_pos:.1f}% positive malignant cells results in heterogeneity score {score:.1f} (0.8x beta penalty)."
        )

    score = round(score, 2)
    return ScoreAxisResult(
        axis_name="heterogeneity_penalty",
        score=score,
        weight=0.10,
        weighted_score=round(score * 0.10, 3),
        confidence="high",
        status="scored",
        rationale=rationale,
        sources=list({s.identifier: s for s in sources}.values()),
    )


def _score_internalization_suitability(
    evidence: EvidenceBundle, isotope: str
) -> ScoreAxisResult:
    """
    Computes internalization score.
    Matters more for residualising beta emitters (Lu-177) where intracellular trapping is vital.
    """
    claim = evidence.target_biology.get("internalization_suitability")
    sources = claim.sources if claim else []

    status_val = str(claim.value).lower() if claim and claim.value else "moderate"

    if "rapid" in status_val:
        base_score = 9.5
    elif "moderate" in status_val:
        base_score = 7.0
    elif "slow" in status_val:
        base_score = 5.0
    else:
        base_score = 2.0

    is_residualising_beta = isotope in ["Lu-177", "Tb-161", "Y-90"]
    if is_residualising_beta:
        rationale = f"Residualising beta isotope ({isotope}) benefits strongly from rapid endocytosis and lysosomal trapping. Score: {base_score:.1f}."
    else:
        rationale = f"Isotope context ({isotope}): Rapid internalization evaluated at score {base_score:.1f}."

    return ScoreAxisResult(
        axis_name="internalisation_suitability",
        score=base_score,
        weight=0.10,
        weighted_score=round(base_score * 0.10, 3),
        confidence=claim.confidence if claim else "medium",
        status="scored",
        rationale=rationale,
        sources=sources,
    )


def _score_shedding_penalty(evidence: EvidenceBundle) -> ScoreAxisResult:
    """Evaluates soluble shed antigen sink liabilities."""
    claim = evidence.target_biology.get("shedding_risk")
    sources = claim.sources if claim else []

    is_shed = bool(claim.value) if claim and claim.value is not None else False
    if is_shed:
        score = 3.5
        rationale = "Antigen shedding reported; circulating soluble receptor acts as a blood-pool sink."
    else:
        score = 9.5
        rationale = "Minimal to no soluble shedding into circulation; radioligand delivers directly to membrane target."

    return ScoreAxisResult(
        axis_name="shedding_penalty",
        score=score,
        weight=0.10,
        weighted_score=round(score * 0.10, 3),
        confidence=claim.confidence if claim else "high",
        status="scored",
        rationale=rationale,
        caveats=claim.caveats if claim else [],
        sources=sources,
    )


def _score_clinical_pipeline_maturity(evidence: EvidenceBundle) -> ScoreAxisResult:
    """Scores clinical trial and regulatory pipeline maturity."""
    sources: list[SourceRef] = []
    has_phase3_or_approved = False
    has_phase1_2 = False
    n_trials = len(evidence.clinical)

    for trial in evidence.clinical:
        if trial.sources:
            sources.extend(trial.sources)
        p_lower = trial.phase.lower()
        if "phase 3" in p_lower or "phase 4" in p_lower or "approved" in p_lower:
            has_phase3_or_approved = True
        elif "phase 1" in p_lower or "phase 2" in p_lower:
            has_phase1_2 = True

    if has_phase3_or_approved:
        score = 9.5
        rationale = f"Advanced clinical pipeline maturity (Phase 3+ / FDA approved precedents found among {n_trials} trials)."
    elif has_phase1_2:
        score = 7.5
        rationale = f"Active Phase 1/2 clinical development ({n_trials} trials identified)."
    elif n_trials > 0:
        score = 5.5
        rationale = f"Early clinical exploration ({n_trials} trials identified)."
    else:
        score = 3.0
        rationale = "No clinical trials identified on ClinicalTrials.gov for this target/indication."

    return ScoreAxisResult(
        axis_name="clinical_pipeline_maturity",
        score=score,
        weight=0.08,
        weighted_score=round(score * 0.08, 3),
        confidence="high",
        status="scored",
        rationale=rationale,
        sources=list({s.identifier: s for s in sources}.values()),
    )


def _score_tractability(evidence: EvidenceBundle) -> ScoreAxisResult:
    """Scores binder tractability and precedent."""
    claim = evidence.tractability.get("tractability")
    sources = claim.sources if claim else []

    val = float(claim.value) if claim and claim.value is not None else 7.0
    val = round(min(10.0, max(0.0, val)), 2)

    return ScoreAxisResult(
        axis_name="tractability",
        score=val,
        weight=0.07,
        weighted_score=round(val * 0.07, 3),
        confidence=claim.confidence if claim else "medium",
        status="scored",
        rationale=f"Binder tractability and radioligand precedent assessed at {val:.1f}/10.",
        caveats=claim.caveats if claim else [],
        sources=sources,
    )


def compute_target_scorecard(
    evidence: EvidenceBundle,
    weights_path: str | Path | None = None,
) -> Scorecard:
    """
    Computes a deterministic, auditable Scorecard from an EvidenceBundle.

    Guarantees:
    - Same inputs produce byte-identical numeric outputs.
    - Zero model hallucination in numeric scores.
    - Hard gates fire for intracellular proteins (fail_membrane_gate) and ubiquitous expression (fail_selectivity_gate).
    - Withholds score if core expression data is unavailable.
    - 100% of scorecard cells carry source attribution.
    """
    config = load_scoring_config(weights_path)
    tier_caps = config.get("evidence_tier_caps", {})
    oar_weights = config.get("oar_radiosensitivity_weights", {})
    mod_config = config.get("isotope_modulation", {})

    target = evidence.target
    isotope = evidence.isotope_context

    # 1. HARD GATE: Cell-Surface Membrane Accessibility
    cell_surf_claim = evidence.target_biology.get("cell_surface_accessible")
    is_cell_surface = (
        bool(cell_surf_claim.value)
        if cell_surf_claim and cell_surf_claim.value is not None
        else True
    )

    if not is_cell_surface:
        axes = {
            "tumour_selectivity": _score_tumour_selectivity(evidence, tier_caps),
            "oar_safety_margin": _score_oar_safety_margin(
                evidence, isotope, oar_weights, mod_config
            ),
        }
        return Scorecard(
            target=target,
            gene_id=evidence.gene_id,
            indication=evidence.indication,
            isotope_context=isotope,
            total_score=0.0,
            rank=None,
            axes=axes,
            recommendation="fail_membrane_gate",
            failure_reasons=[
                "Intracellular localization: target lacks extracellular cell-surface accessibility. Inaccessible to intact radioligands."
            ],
            caveats=["Target failed cell-surface membrane gate G2."],
            provenance=evidence.provenance,
        )

    # 2. Compute 8 individual axes
    axis_selectivity = _score_tumour_selectivity(evidence, tier_caps)
    axis_oar = _score_oar_safety_margin(evidence, isotope, oar_weights, mod_config)
    axis_single_cell = _score_malignant_cell_specificity(evidence)
    axis_heterogeneity = _score_heterogeneity_penalty(evidence, isotope)
    axis_internalization = _score_internalization_suitability(evidence, isotope)
    axis_shedding = _score_shedding_penalty(evidence)
    axis_clinical = _score_clinical_pipeline_maturity(evidence)
    axis_tractability = _score_tractability(evidence)

    axes: dict[str, ScoreAxisResult] = {
        "tumour_selectivity": axis_selectivity,
        "oar_safety_margin": axis_oar,
        "malignant_cell_specificity": axis_single_cell,
        "heterogeneity_penalty": axis_heterogeneity,
        "internalisation_suitability": axis_internalization,
        "shedding_penalty": axis_shedding,
        "clinical_pipeline_maturity": axis_clinical,
        "tractability": axis_tractability,
    }

    # 3. Check for Withheld Score
    if axis_selectivity.status == "withheld":
        return Scorecard(
            target=target,
            gene_id=evidence.gene_id,
            indication=evidence.indication,
            isotope_context=isotope,
            total_score=None,
            rank=None,
            axes=axes,
            recommendation="withheld_insufficient_evidence",
            failure_reasons=["score withheld — expression evidence unavailable"],
            caveats=["Expression specialist could not retrieve validated T/N ratio."],
            provenance=evidence.provenance,
        )

    # 4. HARD GATE: Tumour Selectivity Gate
    if axis_selectivity.score is not None and axis_selectivity.score < 2.0:
        return Scorecard(
            target=target,
            gene_id=evidence.gene_id,
            indication=evidence.indication,
            isotope_context=isotope,
            total_score=round(axis_selectivity.score, 2),
            rank=None,
            axes=axes,
            recommendation="fail_selectivity_gate",
            failure_reasons=[
                f"Ubiquitous normal expression (T/N ratio < 2.0x). Fails tumour selectivity threshold."
            ],
            caveats=["Target failed tumour selectivity gate G2."],
            provenance=evidence.provenance,
        )

    # 5. Compute Weighted Total Score
    total_weighted = 0.0
    total_weights = 0.0
    for ax in axes.values():
        if ax.score is not None and ax.status == "scored":
            total_weighted += ax.score * ax.weight
            total_weights += ax.weight

    final_total = (
        round(total_weighted / total_weights, 2) if total_weights > 0 else 0.0
    )

    if final_total >= 7.5:
        recommendation = "high_priority"
    elif final_total >= 5.5:
        recommendation = "moderate_priority"
    else:
        recommendation = "low_priority"

    return Scorecard(
        target=target,
        gene_id=evidence.gene_id,
        indication=evidence.indication,
        isotope_context=isotope,
        total_score=final_total,
        rank=None,
        axes=axes,
        recommendation=recommendation,
        failure_reasons=[],
        caveats=[],
        provenance=evidence.provenance,
    )
